### ISSUE TITLE
Is it possible to make the optionally linter warnings actually errors

### ISSUE THREAD

**Issue by MichaelTaylor3d** [vkbansal/eslint-plugin-jsx-control-statements#16]
We were interested in making the linter warnings come out as errors that would block a push. Is there a way to do that with the recommended rules?

**Comment by vkbansal** [comment]
I'm afraid, the answer is no. You must manually override them and set to throw errors.

**Comment by MichaelTaylor3d** [comment]
sounds good, thats exactly what we ended up doing. Thanks
