### ISSUE TITLE
'If' is not defined  react/jsx-no-undef

### ISSUE THREAD

**Issue by anilnamde** [vkbansal/eslint-plugin-jsx-control-statements#25]
While running lint I am getting an error trying few things but now able to fix it. Considering the jsx-control-statements are injected with babel instead of import it seems it is not defined. Any inputs how can this be fixed

'If' is not defined  react/jsx-no-undef

**Comment by vkbansal** [comment]
https://eslint.org/docs/user-guide/configuring#specifying-globals

**Comment by anilnamde** [comment]
Tried adding "If" in global but did not help then finally adding following in rules helped fix it

`"react/jsx-no-undef": [ "error", { "allowGlobals": true }]`

**Comment by vkbansal** [comment]
Yeah that is exactly stated here https://github.com/vkbansal/eslint-plugin-jsx-control-statements#important
