### ISSUE TITLE
Require index?

### ISSUE THREAD

**Issue by texttechne** [vkbansal/eslint-plugin-jsx-control-statements#8]
I don't see the use case: Why should anyone enforce an index attribute for _every_ `<For>` loop?
- It's not best practice, but more likely an unused variable
- It's not a pitfall
- It's not any kind of code style preference

Did I miss something or what's the reasoning behind `jsx-control-statements/jsx-for-require-index`?

**Comment by vkbansal** [comment]
Yes you are probably right. Will look into removing this rule

**Comment by vkbansal** [comment]
removed
